apiVersion: v1
kind: Service
metadata:
  name: student-management-svc
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-dlt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - image: naveen1531/student-management:10
        name: student_management
        ports:
        - containerPort: 8080
